export const pendingCourses: ICourseListItem[] = [
  {
    id: 1,
    title: "Advanced JavaScript",
    slug: "advanced-javascript",
    status: "PENDING",
    coverImage: "/images/course-img.png",
    priceAmount: 399000,
    isFree: true,
    createdAt: "2024-07-28",
    students: 0,
    rating: 0,
  },
  {
    id: 2,
    title: "CSS Grid and Flexbox",
    slug: "css-grid-and-flexbox",
    status: "PENDING",
    coverImage: "/images/course-img.png",
    priceAmount: 459000,
    isFree: true,
    createdAt: "2024-07-27",
    students: 0,
    rating: 0,
  },
];

export const publishedCourses: ICourseListItem[] = [
  {
    id: 3,
    title: "Introduction to React",
    slug: "introduction-to-react",
    status: "PUBLISHED",
    coverImage: "/images/course-img.png",
    priceAmount: 350000,
    isFree: false,
    createdAt: "2024-07-26",
    students: 100,
    rating: 4.5,
  },
  {
    id: 4,
    title: "Next.js for Beginners",
    slug: "next-js-for-beginners",
    status: "PUBLISHED",
    coverImage: "/images/course-img.png",
    priceAmount: 450000,
    isFree: false,
    createdAt: "2024-07-25",
    students: 150,
    rating: 4.8,
  },
  {
    id: 5,
    title: "Python for Data Science",
    slug: "python-for-data-science",
    status: "PUBLISHED",
    coverImage: "/images/course-img.png",
    priceAmount: 550000,
    isFree: false,
    createdAt: "2024-07-24",
    students: 200,
    rating: 4.9,
  },
];
